# install.packages("xlsx")
# install.packages("data.table")
# install.packages("ggplot2")

library(xlsx)
library(data.table)
library(ggplot2)

data <- read.xlsx("빅데이터페스티벌DB_S&P종목_001.xlsm", sheetIndex = 3)
data[,1] <- paste(substr(data[,1], 3, 4), substr(data[,1],6,7), sep = '')
data[,1] <- as.numeric(data[,1])

data_table <- fread("빅데이터페스티벌DB_S&P종목_001.csv", sep = ',')
data_table$time <- substr(data_table$time, 3, 7)data_table$time <- substr(data_table$time, 3, 7)
colnames(data_table)[1] <- 'time'
colnames(data_table)[2] <- 'apple'


View(data_table)
View(data)
ggplot(data = data_table, aes(x=time, y=apple))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,2]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,3]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,4]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,5]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,6]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,7]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,8]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,9]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,10]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,11]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,12]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,13]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,14]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,15]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,16]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,17]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,18]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,19]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,20]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,21]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,22]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,23]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,24]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,25]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,26]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,27]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,28]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,29]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,30]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,31]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,32]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,33]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,34]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,35]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,36]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,37]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,38]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,39]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,40]))+geom_point()+theme(axis.text.x = element_text(angle = 45, size = 5))

ggplot(data = data, aes(x=data[,1], y=data[,94]))+geom_point()+geom_line()+theme(axis.text.x = element_text(angle = 45, size = 5))
ggplot(data = data, aes(x=data[,1], y=data[,94]))+geom_line()+theme(axis.text.x = element_text(angle = 45, size = 5))

